<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="EPPlus">
      <HintPath>..\PlanningSchedule\bin\Debug\EPPlus.dll</HintPath>
    </Reference>
    <Reference Include="EPPlus.Interfaces">
      <HintPath>..\PlanningSchedule\bin\Debug\EPPlus.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="EPPlus.System.Drawing">
      <HintPath>..\PlanningSchedule\bin\Debug\EPPlus.System.Drawing.dll</HintPath>
    </Reference>
    <Reference Include="NewExportExcels">
      <HintPath>..\PlanningSchedule\bin\Debug\NewExportExcels.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\PlanningSchedule\bin\Debug\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="SJeMES_Control_Library">
      <HintPath>..\PlanningSchedule\bin\Debug\SJeMES_Control_Library.dll</HintPath>
    </Reference>
    <Reference Include="SJeMES_Framework">
      <HintPath>..\PlanningSchedule\bin\Debug\SJeMES_Framework.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="PlanningSchdule_Reports.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>